export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DMX_ADDRESS_OVERLAP: "DMX_ADDRESS_OVERLAP",
  DMX_ADDRESS_OUT_OF_RANGE: "DMX_ADDRESS_OUT_OF_RANGE",
  FIXTURE_IN_USE: "FIXTURE_IN_USE",
  TRACK_LOCKED: "TRACK_LOCKED"
} as const;
