export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DMX_ADDRESS_INVALID: "DMX_ADDRESS_INVALID",
  DMX_OUT_OF_RANGE: "DMX_OUT_OF_RANGE",
  DMX_ADDRESS_OVERLAP: "DMX_ADDRESS_OVERLAP",
  FIXTURE_IN_SCENE: "FIXTURE_IN_SCENE",
  TRACK_LOCKED: "TRACK_LOCKED"
} as const;
